# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: Tableau Embed
  description: Embeds a Tableau visualization
  icon: image
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  viz_id: ""
  workbook: ""
  sheet: ""
  width: "1000"
  height: "850"
  toolbar: true
  tabs: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  viz_id: "viz1768489152106"
  workbook: "AdventureWorks-PostPublish"
  sheet: "Customers"
  width: "1000"
  height: "850"
  toolbar: true
  tabs: true
